development:
  adapter: postgresql
  encoding: unicode
  database: ondevamos_development
  pool: 5
  username: ondevamos
  password: ondevamos
  host: 127.0.0.1
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: ondevamos_test
  pool: 5
  username: ondevamos
  password: ondevamos
  host: 127.0.0.1
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: ondevamos_production
  pool: 5
  username: ondevamos
  password:
  host: 
